<h1 style="text-align:center;">Dasar Pemrograman Python</h1>
<h3 style="text-align:center;">Fadjar Fathurrahman</h3>

# Beberapa cara menggunakan Python

Beberapa cara untuk menggunakan Python:

1. Interpreter atau konsol Python standard.
2. Konsol interaktif Python (IPython).
3. Jupyter notebook dan Jupyter lab.
4. Menggunakan IDE.

Dokumen ini dibuat dengan menggunakan Jupyter notebook. Dengan menggunakan Jupyter notebook, kita dapat menggabungkan antara narasi teks dan kode.

# Menggunakan Python sebagai kalkulator

## Operasi aritmatika sederhana

Python dapat digunakan sebagai kalkulator untuk melakukan berbagai perhitungan matematika.

Penjumlahan:

In [1]:
2 + 3

5

Pengurangan

In [2]:
2 - 3.1

-1.1

Perkalian

In [3]:
2.3*4*3.1

28.52

Pembagian

In [4]:
2/3

0.6666666666666666

Selain pembagian biasa, Python juga menyediakan operator untuk pembagian bilangan bulat (integer)

In [5]:
2//3

0

In [6]:
4//3

1

Operator modulo (sisa pembagian)

In [7]:
4%3

1

In [8]:
100%7

2

In [9]:
10%5

0

Untuk melakukan beberapa operasi perhitungan sekaligus dalam satu input bisa digunakan tanda koma:

In [10]:
100//7, 100%7

(14, 2)

In [11]:
14*7 + 2

100

## Komentar

Komentar perbaris pada Python dapat ditandai dengan simbol `#`.

Contoh:

```python
# Ini komentar
a = 3 + 7 # ini juga komentar
```

## Fungsi-fungsi matematika

Fungsi-fungsi matematika seperti sin, cos, log, exp dan sebagainya dapat diakses dengan cara mengimport modul `math`. Dalam modul ini juga didefinisikan beberapa konstanta seperti bilangan $\pi$ dan konstanta Euler $e$.

Ada beberapa sintaks untuk mengimpor modul.

**Cara 1**

```python
from nama_module import nama_fungsi1, nama_fungsi2, konstanta1
```

Dengan cara ini, kita dapat langsung menggunakan `nama_fungsi1`, `nama_fungsi1`, `nama_fungsi2` dan `konstanta1` pada kode. Fungsi-fungsi lain yang tidak kita impor tidak bisa digunakan, meskipun fungsi atau konstanta tersebut ada pada modul yang bersangkutan. Contoh:

```python
from math import sin, cos
```

Dengan kode di atas kita hanya mengimport fungsi `sin` dan `cos`, sedangkan fungsi-fungsi lain seperti `tan`, `log`, dan sebagainya tidak akan diimpor (tidak terdefinisi pada sesi atau scope yang sedang aktif).

Jika Anda ingin mengimport semua simbol (konstanta dan fungsi) dapat dilakukan dengan menggunakan *wildcard* `*`:

```python
from math import * # mengimport semua simbol dari modul math
```

**Cara 2**

```python
import math
```

Dengan cara ini kita tidak mengimpor fungsi apapun, namun hanya modul `math` saja. Meskipun demikian kita dapat menggunakan fungsi yang didefinisikan pada modul `math` dengan menggunakan `math.nama_fungsi` atau `math.nama_konstanta`, misalnya:

```python
math.pi     # mengakses konstanta pi
math.sin(math.pi/3) # memanggil fungsi sin
```

Nama saya adalah efefer. 

Contoh teks **bold**.

Contoh teks *italic*

List:

- Contoh 1
- Contoh 2

List

1. Contoh A
2. Contoh B

Contoh inline equation.

Contoh persamaan $\alpha + \beta - \gamma$. Misalkan $v$ adalah kecepatan.

Contoh display equation:

$$
\int f(x) dx = \frac{\Gamma}{1 - x}
$$

$$
\frac{1}{2}\nabla^2
$$

In [1]:
import math
import cmath

In [4]:
math.sqrt(4)

2.0

In [5]:
cmath.sqrt(4)

(2+0j)

In [9]:
math.sqrt(-1)

ValueError: math domain error

In [10]:
cmath.sqrt(-1)

1j

$$
\exp\left(\imath\pi\right) = \cos(\pi) + \imath \sin(\pi) = -1
$$

In [12]:
math.pi

3.141592653589793

In [13]:
cmath.exp(1j*math.pi)

(-1+1.2246467991473532e-16j)

In [2]:
from math import sin, cos, pi # sin, cos, dan pi dapat langsung digunakan
x = sin(2*pi/3) + cos(2*pi/3)
x

0.36602540378443893

In [4]:
import math
x = math.sin(2*math.pi/3) + cos(2*math.pi/3)
x

0.36602540378443893

# Variabel dan tipe data

Untuk mendeklarasikan variabel pada Python, kita dapat menggunakan operator penugasan (*assignment*) yaitu dengan tanda `=`

In [14]:
a = 3.4
b = 1
c = a + b

**Catatan**: Pada Jupyter notebook, hasil perhitungan tidak akan ditampilkan jika kita menggunakan operator penugasan. Untuk melihat hasil perhitungan atau nilai variabel kita dapat mengetikkan nama variabel pada suatu sel dan mengeksekusi sel tersebut.

In [15]:
c

4.4

In [16]:
a, b, c

(3.4, 1, 4.4)

Python memiliki banyak tipe data, di antaranya yang sering dipakai adalah:

1. Integer (`int`)
2. Float (`float`)
3. String (`str`)
4. Boolean (`bool`)

Untuk mengetahui tipe suatu variabel kita dapat menggunakan fungsi `type`:

In [17]:
type(a), type(b), type(c)

(float, int, float)

Contoh variabel dengan tipe `String`:

In [15]:
nama1 = "Jojo"
nama2 = "Sujojo"
type(nama1), type(nama2)

(str, str)

Tipe data boolean hanya memiliki dua nilai yang mungkin yaitu: `True` dan `False`

In [16]:
kondisi1 = True
kondisi2 = False
type(kondisi1), type(kondisi2)

(bool, bool)

Nama variabel pada Python mengikuti aturan yang kurang lebih sama dengan penamaan variabel dalam bahasa C/C++.

Contoh nama variabel yang valid:

```python
my_name = "Jojo
MyName = "Sujojo"
x1 = 2.3
```

Contoh nama variabel yang tidak valid:
```python
for = 1  # menggunakan kata kunci for
1a = 4 # diawali dengan angka
```

In [18]:
nama = "efefer"
print("Nama saya adalah ", nama)

Nama saya adalah  efefer


## Tipe bilangan kompleks

Selain tipe bilangan bulat (`int`) dan real (`float`), Python juga mendukung tipe bilangan kompleks secara default. Bagian imajiner dari bilangan kompleks dapat dinyatakan dengan menambahkan `j` setelah bagian imajiner.

In [17]:
z1 = 2 + 3j
z2 = 4 + 4.5j
z1 + z2

(6+7.5j)

In [18]:
type(z1)

complex

Perhatikan bahwa bilangan imajiner murni $\sqrt{-1}=\textrm{i}$ dinyatakan dengan `1j`, bukan `j`:

```
1j
```

Jika kita hanya menggunakan `j`:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-3eedd8854d1e> in <module>
----> 1 j

NameError: name 'j' is not defined
```

Member `real` dan `imag` dapat digunakan untuk mengakses bagian real dan imajiner dari bilangan kompleks. Metode `conjugate()` dapat digunakan untuk mendapatkan konjugat kompleks.

In [19]:
z1.real, z2.imag, z1.conjugate()

(2.0, 4.5, (2-3j))

In [20]:
z1*z2

(-5.5+21j)

In [21]:
z1/z2

(0.593103448275862+0.08275862068965516j)

In [22]:
z1*z1.conjugate()

(13+0j)

In [23]:
(z1*z1.conjugate()).real

13.0

In [24]:
(z1*z1.conjugate()).imag

0.0

### String

String merepresentasikan data teks.

Dalam perhitungan numerik string tidak terlalu banyak digunakan. Namun untuk beberapa aplikasi lain seperti parsing dan analisis teks pengetahuan mengenai string sangat diperlukan. Topik mengenai string sangat luas dan kita hanya akan membahas beberapa hal saja.

Ada beberapa cara untuk menggunakan tipe data string.

- Menggunakan tanda petik tunggal: `'Nama saya Jojo'`
- Menggunakan tanda petik ganda: `"Nama saya Jojo"`

Untuk string yang lebih panjang dapat digunakan tidak tanda petik, baik tunggal atau ganda.

Dalam tutorial ini, akan digunakan tanda petik dua untuk menyatakan string. Anda dapat menggantinya dengan menggunakan tanda petik tunggal jika Anda lebih suka.

In [19]:
nama1 = 'Jojo'
nama2 = "Jojo"
nama1, nama2

('Jojo', 'Jojo')

In [20]:
type(nama1)

str

Contoh string panjang yang memakan lebih dari satu baris.

In [4]:
lirik_lagu = """
Aku ingin begini
Aku ingin begitu
Ingin ini ingin itu
banyak sekali
"""
lirik_lagu

'\nAku ingin begini\nAku ingin begitu\nIngin ini ingin itu\nbanyak sekali\n'

String dapat dianggap sebagai kumpulan dari karakter-karakter individual.

Untuk mengakses karakter individual dapat digunakan operator indexing `[]`. Indeks pada Python dimulai dari 0.

In [21]:
nama1

'Jojo'

In [7]:
nama1[0], nama1[1], nama2[2]

('J', 'o', 'j')

Untuk mengetahui panjang suatu string dapat digunakan fungsi `len`.

In [8]:
len(nama1)

4

Perhatikan bahwa tipe dari karakter-karakter pada string adalah string juga (bukan `char` seperti pada C/C++).

In [9]:
type(nama1[0])

str

Beberapa operator matematika dapat digunakan pada string, namun operasinya berbeda dengan operasi matematika biasa.

In [13]:
"Nama" + " " + "saya" + " adalah " + "Jojo"

'Nama saya adalah Jojo'

In [14]:
"Jojo"*2

'JojoJojo'

In [22]:
str1 = "saya"

In [23]:
str1.capitalize()

'Saya'

In [21]:
str1.casefold()

'saya'

In [24]:
str1.count("a")

2

In [25]:
lirik_lagu.split()

['Aku',
 'ingin',
 'begini',
 'Aku',
 'ingin',
 'begitu',
 'Ingin',
 'ini',
 'ingin',
 'itu',
 'banyak',
 'sekali']

In [27]:
lirik_lagu.upper()

'\nAKU INGIN BEGINI\nAKU INGIN BEGITU\nINGIN INI INGIN ITU\nBANYAK SEKALI\n'

In [28]:
lirik_lagu.lower()

'\naku ingin begini\naku ingin begitu\ningin ini ingin itu\nbanyak sekali\n'

String dapat dianggap sebagai kumpulan berurut dari beberapa karakter atau huruf individual.
Kumpulan berurut ini sering disebut sebagai list. List pada Python memiliki beberapa operasi yang dapat digunakan, salah satunya adalah indexing dan slicing. Anda dapat mempelajari lebih lanjut mengenai list di bagian tipe data kontainer.

Contoh operasi slicing pada string.

In [29]:
lirik_lagu[0:9:2]

'\nk ni'

In [30]:
lirik_lagu[::-1]

'\nilakes kaynab\nuti nigni ini nignI\nutigeb nigni ukA\ninigeb nigni ukA\n'

## Tipe data kontainer

### List

List mirip dengan array pada bahasa pemrograman C/C++. Salah satu perbedaannya adalah tipe elemen pada list tidak perlu terdiri dari tipe yang sama. Selain itu, list juga mendukung beberapa operasi yang lebih kompleks dibandingkan dengan array pada C/C++.

In [25]:
mylst1 = [3, 5, 7, 11, 44, 33, 88, 99]
mylst1

[3, 5, 7, 11, 44, 33, 88, 99]

In [26]:
type(mylst1)

list

Contoh list dengan elemen-elemen yang terdiri dari tipe data berbeda.

In [27]:
mylst2 = ["Nama", 1, 2.3, True]
mylst2

['Nama', 1, 2.3, True]

Untuk mengakses elemen pada list kita dapat menggunakan operator indexing `[]`. Indeks pada Python dimulai dari 0.

In [28]:
mylst1[0], mylst1[3]

(3, 11)

Indeks negatif juga dapat digunakan pada list:

In [29]:
mylst1[-1], mylst1[-2], mylst1[-3], mylst1[-4]

(99, 88, 33, 44)

Untuk mengetahui panjang (jumlah element) suatu list dapat digunakan fungsi builtin `len()`:

In [30]:
len(mylst1), len(mylst2)

(8, 4)

List mendukung operasi slicing. Operasi ini mengembalikan (sub)list dari list awal. Sintaks yang digunakan adalah:
```python
mylist[idx_awal:idx_akhir:increment]
```
Dengan sintaks di atas akan dikembalikan sebuah list dengan element dari `mylist[idx_awal]` sampai sebelum `my_list[idx_akhir]` dengan penambahan indeks `increment`.
Pada operasi slicing tidak harus semua paramter diberikan. Secara default `idx_awal = 0`, `idx_akhir = len(my_list)`, dan `increment = 1`.

In [31]:
mylst1[1:3]

[5, 7]

In [32]:
mylst1[0:8:2]

[3, 7, 44, 88]

In [33]:
mylst1[:3]

[3, 5, 7]

In [34]:
mylst1[0:]

[3, 5, 7, 11, 44, 33, 88, 99]

In [35]:
mylst1[::2]

[3, 7, 44, 88]

In [36]:
mylst1[::-1]

[99, 88, 33, 44, 11, 7, 5, 3]

List bersifat **mutable**, artinya elemen list dapat diubah.

In [37]:
mylst1[0] = 1000
mylst1

[1000, 5, 7, 11, 44, 33, 88, 99]

Elemen baru dapat ditambahkan ke list dengan menggunakan metode `append`:

In [38]:
mylst1.append(123)
mylst1

[1000, 5, 7, 11, 44, 33, 88, 99, 123]

Beberapa operator yang normal digunakan pada perhitungan matematika seperti `+` memiliki arti tertentu pada list. Misalnya

In [39]:
mylst1 = mylst1 + [1000]
mylst1

[1000, 5, 7, 11, 44, 33, 88, 99, 123, 1000]

In [49]:
mylst1 + [3, 4, 5]

[1000, 5, 7, 11, 44, 33, 88, 99, 123, 1000, 3, 4, 5]

Elemen dari suatu list dapat juga berupa list yang lain. Pada perintah berikut kita akan menambahkan suatu list yaitu `[3,4,5]` pada `my_list`.

In [50]:
mylst1.append([3,4,5])

In [51]:
mylst1

[1000, 5, 7, 11, 44, 33, 88, 99, 123, 1000, [3, 4, 5]]

List pada Python juga mendukung beberapa operasi lain. Untuk memperoleh gambaran lebih lengkap, Anda dapat membaca di
[https://docs.python.org/3/tutorial/datastructures.html#more-on-lists](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists)

### Tupel

Tupel sangat mirip dengan list. Perbedaan pentingnya adalah tupel bersifat **immutable**. Tupel dapat diinisialisasi dari elemen-elemennya dengan menggunakan tanda `()` dan diantara elemen dipisahkan dengan tanda koma.

In [40]:
mytpl = (0, "3", True, 1.3)
mytpl

(0, '3', True, 1.3)

In [41]:
type(mytpl)

tuple

Tupel juga dapat diinisialisasi tanpa menggunakan tanda `()`.

In [42]:
mytpl = 0, "3", True, 1.3
mytpl

(0, '3', True, 1.3)

In [43]:
mytpl[1:3]

('3', True)

Seperti yang telah diinfomasikan sebelumnya, berbeda dengan list, tupel bersifat **immutable**, artinya elemen-elemennya tidak dapat dimodifikasi setelah diinisialisasi.

Kode berikut ini akan memberikan kesalahan
```python
mytpl[0] = 3.4
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-44-77d297c1309c> in <module>()
----> 1 mytpl[0] = 3.4

TypeError: 'tuple' object does not support item assignment
```

Karena bersifat immutable, tupel tidak memiliki operasi sefleksibel list. Meskipun demikian kita dapat mengubah tupel menjadi list dengan menggunakan konstruktor `list`.

In [63]:
mylst3 = list(mytpl)
mylst3

[0, '3', True, 1.3]

In [64]:
mylst3[0] = 44
mylst3

[44, '3', True, 1.3]

### Set (himpunan)

Tipe data set pada Python terdiri dari elemen-elemen unik yang tidak berulang. Urutan tidak terdefinisi pada set. Set dapat diinisialisasi dari elemen-elemennya dengan menggunakan tanda kurung kurawal.

In [68]:
myset = {0, 0, 2, 4, 11, 11, 100, 100, "A", "B", True, (3,4)}
myset

{(3, 4), 0, 100, 11, 2, 4, 'A', 'B', True}

Set juga dapat diinisialisasi dengan menggunakan konstruktor `set` dengan sintaks umum sebagai berikut:
```python
set(iterable_data)
```
di mana `iterable_data` merupakan tipe data yang dapat diiterasi seperti list, tupel, string dan sebagainya.

In [70]:
set("Aku ingin begini. Aku ingin begitu")

{' ', '.', 'A', 'b', 'e', 'g', 'i', 'k', 'n', 't', 'u'}

In [72]:
set([1, 3, 4, 6, 7, 8, 8, 9, 7, 4, 3, 2])

{1, 2, 3, 4, 6, 7, 8, 9}

In [78]:
buah2an = ("apel", "mangga", "pisang", "jeruk", "apel", "pisang")
set( buah2an )

{'apel', 'jeruk', 'mangga', 'pisang'}

### Dictionary (kamus)

Dictionary atau `dict` pada Python adalah suatu tipe data yang terdiri dari kumpulan pasangan key (kunci) dan value (nilai). Tipe data `dict` bersifat mutable. Anda dapat menganggap `dict` sebagai tabel yang terdiri dari dua kolom, di mana key berada pada kolom pertama dan value pada kolom kedua. Dalam beberapa bahasa pemrograman lain, `dict` sering juga disebut sebagai array asosiatif.

In [23]:
nilai = {"Jojo": 100, "Jono": 80, "Koko": 65, "Bobo": 44}
nilai

{'Jojo': 100, 'Jono': 80, 'Koko': 65, 'Bobo': 44}

In [9]:
type(nilai)

dict

Anda dapat mengakses nilai dari "Jojo", misalnya, dengan menggunakan:

In [8]:
nilai["Jojo"]

100

Fungsi `list` dapat digunakan untuk mendapatkan semua `key` dari suatu `dict`:

In [12]:
list(nilai)

['Jojo', 'Jono', 'Koko', 'Bobo']

Anda dapat menambahkan pasangan `key` dan `value` baru seperti pada contoh berikut

In [16]:
nilai["Aan"] = 70
nilai

{'Jojo': 100, 'Jono': 80, 'Koko': 65, 'Bobo': 44, 'Aan': 70}

Selain dengan menggunakan operasi indexing langsung, metode `update` juga dapat digunakan untuk mengubah suatu `dict`:

In [24]:
nilai["Jojo"] = 40
nilai["Aan"] = 55
nilai

{'Jojo': 40, 'Jono': 80, 'Koko': 65, 'Bobo': 44, 'Aan': 55}

In [25]:
nilai.update({"Jojo": 99, "Aan": 88})
nilai

{'Jojo': 99, 'Jono': 80, 'Koko': 65, 'Bobo': 44, 'Aan': 88}

Fungsi `del` dapat digunakan untuk menghapus key dan value pada `dict`.

In [26]:
del nilai["Jono"]

In [27]:
nilai

{'Jojo': 99, 'Koko': 65, 'Bobo': 44, 'Aan': 88}

## Kontrol alur program

### Kondisional

Pernyataan kondisional digunakan untuk melakukan atau tidak melakukan suatu pernyataan dalam program berdasarkan suatu kondisi tertentu.

Pernyataan kondisional dapat dibuat dengan menggunakan kata-kata kunci `if`, `else`, dan `elif`.

Sintaks `if`
```python
if kondisi:
    lakukan_sesuatu
```

Sintaks `if-else`
```python
if kondisi_a:
    lakukan_ini
else:
    lakukan_itu
```

Sintaks `if-elif-else`
```python
if kondisi_a:
    lakukan_ini
elif kondisi_b:
    lakukan_itu
else:
    lakukan_yang_lain
```

Berikut ini adalah operator-operator logika dalam Python (Referensi: Huff, *Effective Computation in Physics - Field Guide to research in Python*)

**Unary operator**

| Name | Usage | Returns |
| ---- | ----- | ------- |
| Negation | `not x` | Logical negation - `True` becomes False , and vice versa. |
| Bitwise invert | `~x` | Changes all zeros to ones and vice versa in `x`'s binary representation.|

**Binary operators**

| Name | Usage | Returns |
| ---- | ----- | ------- |
| Logical and | `x and y` | `True` if `bool(x)` and `bool(y)` are `True` ; False otherwise. |
| Logical or | `x or y` | `x` if `bool(x)` is `True` ; otherwise the value of y . |

**Comparison binary operators**

| Name | Usage | Returns |
| ---- | ----- | ------- |
| Equality | `x == y` | `True` or `False` |
| Not equal | `x != y` | `True` or `False` |
| Less than | `x < y` | `True` or `False` |
| Less than or equal | `x <= y` | `True` or `False` |
| Greater than | `x > y` | `True` or `False` |
| Greater than or equal | `x >= y` | `True` or `False` |
| Containment | `x in y` | `True` if `x` is an element of `y` |
| Non-containment | `x not in y` | `False` if `x` is an element of `y` |
| Identity test | `x is y` | `True` if `x` and `y` point to the same underlying value in memory |


In [29]:
a = -1
if a > 0:
    print("a bernilai positif")
else:
    print("a bernilai negatif")

a bernilai negatif


In [30]:
a = 0
if a > 0:
    print("a bernilai positif")
elif a < 0:
    print("a bernilai negatif")
else:
    print("a bernilai 0")

a bernilai 0


In [32]:
mylist = [1, 2, 3, 4, 6]
if 5 in mylist:
    print("Nilai 5 berada dalam mylist")
else:
    print("Nilai 5 tidak ada dalam list")

Nilai 5 tidak ada dalam list


In [33]:
nilai = {"Jojo": 100, "Jono": 80, "Koko": 65, "Bobo": 44}
if "Jojo" not in nilai:
    print("Jojo tidak ada dalam dict nilai")
else:
    print("Jojo ada dalam dict nilai")

Jojo ada dalam dict nilai


### Loop (pengulangan)

Ada beberapa cara untuk melakukan operasi pengulangan pada Python.

Beberapa yang sering digunakan adalah pernyataan dengan kata kunci `while` dan `for`.

Sintaks:
```python
while kondisi:
    lakukan_sesuatu
```

Sintaks:
```python
for variabel in iterable:
    lakukan_sesuatu
```

Contoh `iterable` adalah list, dict, dan set. `iterable` juga dapat dihasilkan dengan menggunakan fungsi `range`.

In [3]:
a = 0
while a < 10:
    print("a = %d" % a)
    a = a + 1

a = 0
a = 1
a = 2
a = 3
a = 4
a = 5
a = 6
a = 7
a = 8
a = 9


In [6]:
for a in range(1,10):
    print("a = %d" % a)

a = 1
a = 2
a = 3
a = 4
a = 5
a = 6
a = 7
a = 8
a = 9


Kata kunci `break` dapat digunakan untuk menghentikan loop jika suatu kondisi terpenuhi.

In [7]:
a = 0
while True:
    if a >= 10:
        break
    print("a = %d" % a)
    a = a + 2

a = 0
a = 2
a = 4
a = 6
a = 8


In [8]:
for i in range(10):
    if i == 5:
        continue
    print("i = %d" % i)

i = 0
i = 1
i = 2
i = 3
i = 4
i = 6
i = 7
i = 8
i = 9


In [28]:
for nama in nilai:
    print("nama = ", nama)

nama =  Jojo
nama =  Koko
nama =  Bobo
nama =  Aan


### Exception

Exception adalah suatu mekanisme pada bahasa pemrograman untuk mengatasi atau menginformasikan bahwa terlah terjadi suatu kesalahan seperti kesalahan input argumen, file tidak ditemukan dan sebagainya.

In [34]:
x = 0
try:
    a = 1/x
except:
    print("x tidak boleh 0")

x tidak boleh 0


Python mendukung banyak sekali tipe exception, salah satu yang sering digunakan adalah `RuntimeException`. Anda dapat menggunakan exception ini jika terjadi kesalahan pada program Anda.

Contoh:

```python
a = -1.0
if a < 0:
    raise RuntimeError("a harus lebih besar dari 0")
```

akan memberikan keluaran:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-38-87e95f0d6c82> in <module>()
      1 a = -1.0
      2 if a < 0:
----> 3     raise RuntimeError("a harus lebih besar dari 0")

RuntimeError: a harus lebih besar dari 0
```

## Fungsi (subprogram)

In [ ]:
def my_func_01(a, b):
    return a + b

In [ ]:
def my_func_02(a, b):
    print("a = ", a)
    print("b = ", b)

In [ ]:
def my_func_03(a, b):
    temp = a
    a = b
    b = a

In [ ]:
a = 3
b = 4
c = my_func_01(a, b)
c

In [ ]:
c = my_func_02(a, b)

In [ ]:
type(c)

In [ ]:
my_func_03(a, b)
a, b

In [ ]:
my_func_03(*{a}, b)
a, b

In [ ]:
def my_func_04(a, b):
    return b, a

In [ ]:
a, b = my_func_04(a, b)
a, b

In [ ]:
def my_func_05(args):
    args[0] = 1

In [ ]:
args = [3, 4]
my_func_05(args)
args

## Pengenalan Numpy

In [1]:
import numpy as np

In [3]:
mylist1 = [1, 2, 3, 4, 5]
mylist2 = [4.5, 2, 1.3, 4, 5]

In [5]:
np.array(mylist1)*np.array(mylist2)

array([ 4.5,  4. ,  3.9, 16. , 25. ])

In [7]:
x1 = np.array([1,2,3,4,4])

In [8]:
type(x1)

numpy.ndarray

In [9]:
0.5*x1

array([0.5, 1. , 1.5, 2. , 2. ])

In [15]:
A = np.matrix([[1,2,3,4], [1,3,2,4]])
A

matrix([[1, 2, 3, 4],
        [1, 3, 2, 4]])

In [16]:
A[1,2]

2

In [17]:
A[:,1]

matrix([[2],
        [3]])

In [18]:
A[1,:]

matrix([[1, 3, 2, 4]])

In [44]:
B = np.matrix.copy(A)
B

matrix([[1, 2, 3, 4],
        [1, 3, 2, 4]])

In [45]:
B.transpose()*B

matrix([[ 2,  5,  5,  8],
        [ 5, 13, 12, 20],
        [ 5, 12, 13, 20],
        [ 8, 20, 20, 32]])

In [46]:
?np.linalg.solve

Signature: np.linalg.solve(a, b)
Docstring:
Solve a linear matrix equation, or system of linear scalar equations.

Computes the "exact" solution, `x`, of the well-determined, i.e., full
rank, linear matrix equation `ax = b`.

Parameters
----------
a : (..., M, M) array_like
    Coefficient matrix.
b : {(..., M,), (..., M, K)}, array_like
    Ordinate or "dependent variable" values.

Returns
-------
x : {(..., M,), (..., M, K)} ndarray
    Solution to the system a x = b.  Returned shape is identical to `b`.

Raises
------
LinAlgError
    If `a` is singular or not square.

Notes
-----

.. versionadded:: 1.8.0

Broadcasting rules apply, see the `numpy.linalg` documentation for
details.

The solutions are computed using LAPACK routine _gesv

`a` must be square and of full-rank, i.e., all rows (or, equivalently,
columns) must be linearly independent; if either is not true, use
`lstsq` for the least-squares best "solution" of the
system/equation.

References
----------
.. [1] G. Strang, *Lin

In [48]:
A = np.matrix([[6, -4, 1], [-4, 6, -4], [1, -4, 6]], dtype=np.float64)
b = b = np.matrix([[-14, 36, 6],[22, -18, 7]], dtype=np.float64).transpose()
print(A)
print(b)

[[ 6. -4.  1.]
 [-4.  6. -4.]
 [ 1. -4.  6.]]
[[-14.  22.]
 [ 36. -18.]
 [  6.   7.]]


In [49]:
np.linalg.solve(A,b)

matrix([[ 1.00000000e+01,  3.00000000e+00],
        [ 2.20000000e+01, -1.00000000e+00],
        [ 1.40000000e+01, -1.77635684e-16]])

In [21]:
B[1,:] = 1.0
B

array([[1, 2, 3, 4],
       [1, 1, 1, 1]])

In [22]:
B.shape

(2, 4)

In [23]:
B.trace()

2

In [25]:
B.transpose()

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [28]:
np.matmul(B.transpose(), B)

array([[ 2,  3,  4,  5],
       [ 3,  5,  7,  9],
       [ 4,  7, 10, 13],
       [ 5,  9, 13, 17]])

In [30]:
Bt = B.transpose()
type(Bt), Bt

(numpy.ndarray, array([[1, 1],
        [2, 1],
        [3, 1],
        [4, 1]]))

In [31]:
Bt[1,1] = 0.0
Bt, B

(array([[1, 1],
        [2, 0],
        [3, 1],
        [4, 1]]), array([[1, 2, 3, 4],
        [1, 0, 1, 1]]))

In [40]:
Bt2 = np.matrix(B.transpose())
Bt2

matrix([[1, 1],
        [2, 0],
        [3, 1],
        [4, 1]])

2d `ndarray` sedikit berbeda dengan `matrix`.

In [41]:
Bt2*B

matrix([[ 2,  2,  4,  5],
        [ 2,  4,  6,  8],
        [ 4,  6, 10, 13],
        [ 5,  8, 13, 17]])

In [ ]:
np.matrixlib.

In [39]:
np.matmul(Bt2,B)

array([[ 2,  2,  4,  5],
       [ 2,  4,  6,  8],
       [ 4,  6, 10, 13],
       [ 5,  8, 13, 17]])

In [24]:
?np.trace

Signature: np.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)
Docstring:
Return the sum along diagonals of the array.

If `a` is 2-D, the sum along its diagonal with the given offset
is returned, i.e., the sum of elements ``a[i,i+offset]`` for all i.

If `a` has more than two dimensions, then the axes specified by axis1 and
axis2 are used to determine the 2-D sub-arrays whose traces are returned.
The shape of the resulting array is the same as that of `a` with `axis1`
and `axis2` removed.

Parameters
----------
a : array_like
    Input array, from which the diagonals are taken.
offset : int, optional
    Offset of the diagonal from the main diagonal. Can be both positive
    and negative. Defaults to 0.
axis1, axis2 : int, optional
    Axes to be used as the first and second axis of the 2-D sub-arrays
    from which the diagonals should be taken. Defaults are the first two
    axes of `a`.
dtype : dtype, optional
    Determines the data-type of the returned array and of the 

In [2]:
np.linspace(1, 10, 100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [51]:
import scipy
import scipy.linalg

In [52]:
?scipy.linalg.hilbert

Signature: scipy.linalg.hilbert(n)
Docstring:
Create a Hilbert matrix of order `n`.

Returns the `n` by `n` array with entries `h[i,j] = 1 / (i + j + 1)`.

Parameters
----------
n : int
    The size of the array to create.

Returns
-------
h : (n, n) ndarray
    The Hilbert matrix.

See Also
--------
invhilbert : Compute the inverse of a Hilbert matrix.

Notes
-----
.. versionadded:: 0.10.0

Examples
--------
>>> from scipy.linalg import hilbert
>>> hilbert(3)
array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.5       ,  0.33333333,  0.25      ],
       [ 0.33333333,  0.25      ,  0.2       ]])
File:      ~/mysoftwares/anaconda3/lib/python3.6/site-packages/scipy/linalg/special_matrices.py
Type:      function


In [57]:
H1 = np.matrix(scipy.linalg.hilbert(10))
H1

matrix([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
         0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
        [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
         0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909],
        [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714,
         0.125     , 0.11111111, 0.1       , 0.09090909, 0.08333333],
        [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ,
         0.11111111, 0.1       , 0.09090909, 0.08333333, 0.07692308],
        [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
         0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857],
        [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
         0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667],
        [0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909,
         0.08333333, 0.07692308, 0.07142857, 0.06666667, 0.0625    ],
        [0.125     , 0.1111

In [58]:
type(H1)

numpy.matrixlib.defmatrix.matrix

In [60]:
invH1 = np.linalg.inv(H1)

In [61]:
invH1_v2 = scipy.linalg.invhilbert(10)

In [63]:
?scipy.linalg.invhilbert

Signature: scipy.linalg.invhilbert(n, exact=False)
Docstring:
Compute the inverse of the Hilbert matrix of order `n`.

The entries in the inverse of a Hilbert matrix are integers.  When `n`
is greater than 14, some entries in the inverse exceed the upper limit
of 64 bit integers.  The `exact` argument provides two options for
dealing with these large integers.

Parameters
----------
n : int
    The order of the Hilbert matrix.
exact : bool, optional
    If False, the data type of the array that is returned is np.float64,
    and the array is an approximation of the inverse.
    If True, the array is the exact integer inverse array.  To represent
    the exact inverse when n > 14, the returned array is an object array
    of long integers.  For n <= 14, the exact inverse is returned as an
    array with data type np.int64.

Returns
-------
invh : (n, n) ndarray
    The data type of the array is np.float64 if `exact` is False.
    If `exact` is True, the data type is either np.int64 (for

In [62]:
invH1 - invH1_v2

matrix([[-2.81268089e-03,  2.43145415e-01, -5.18055573e+00,
          4.71063712e+01, -2.24718671e+02,  6.17799847e+02,
         -1.01366278e+03,  9.79601372e+02, -5.14279797e+02,
          1.13095769e+02],
        [ 2.43588526e-01, -2.10482964e+01,  4.48320094e+02,
         -4.07552538e+03,  1.94382199e+04, -5.34311399e+04,
          8.76559096e+04, -8.47007249e+04,  4.44625409e+04,
         -9.77696470e+03],
        [-5.19702606e+00,  4.48927912e+02, -9.55969953e+03,
          8.68878625e+04, -4.14350217e+05,  1.13881405e+06,
         -1.86808066e+06,  1.80494655e+06, -9.47413552e+05,
          2.08315555e+05],
        [ 4.73053792e+01, -4.08530823e+03,  8.69785338e+04,
         -7.90431985e+05,  3.76897299e+06, -1.03577975e+07,
          1.69893270e+07, -1.64140623e+07,  8.61522485e+06,
         -1.89420642e+06],
        [-2.25853713e+02,  1.95009453e+04, -4.15124802e+05,
          3.77208279e+06, -1.79845615e+07,  4.94210108e+07,
         -8.10574990e+07,  7.83087156e+07, -4.109991