In [1]:
import numpy as np

In [38]:
A = np.matrix( [
    [1, 1, 1],
    [2, 3, 1],
    [1, -1, -1]
])
A

matrix([[ 1,  1,  1],
        [ 2,  3,  1],
        [ 1, -1, -1]])

In [41]:
A/2

matrix([[ 0.5,  0.5,  0.5],
        [ 1. ,  1.5,  0.5],
        [ 0.5, -0.5, -0.5]])

In [40]:
A//2

matrix([[ 0,  0,  0],
        [ 1,  1,  0],
        [ 0, -1, -1]])

In [9]:
b = np.array([[1], [2], [1]])
b

array([[1],
       [2],
       [1]])

In [21]:
b = np.matrix([4, 9, 2]).transpose()
b

matrix([[4],
        [9],
        [2]])

In [22]:
A*b

matrix([[15],
        [37],
        [-7]])

In [23]:
A.transpose()

matrix([[ 1,  2,  1],
        [ 1,  3, -1],
        [ 1,  1, -1]])

In [18]:
A

matrix([[ 1,  1,  1],
        [ 2,  3,  1],
        [ 1, -1, -1]])

In [19]:
np.linalg.inv(A)

matrix([[ 0.5 ,  0.  ,  0.5 ],
        [-0.75,  0.5 , -0.25],
        [ 1.25, -0.5 , -0.25]])

In [24]:
np.linalg.inv(A)*b

matrix([[3.],
        [1.],
        [0.]])

In [25]:
A[1,1]

3

Kolom pertama

In [26]:
A[:,0]

matrix([[1],
        [2],
        [1]])

Baris pertama

In [27]:
A[0,:]

matrix([[1, 1, 1]])

In [28]:
A

matrix([[ 1,  1,  1],
        [ 2,  3,  1],
        [ 1, -1, -1]])

In [30]:
A_asli = np.matrix.copy(A)
A_asli

matrix([[ 1,  1,  1],
        [ 2,  3,  1],
        [ 1, -1, -1]])

In [31]:
A[1,:] = A[1,:] - 2*A[0,:]
A

matrix([[ 1,  1,  1],
        [ 0,  1, -1],
        [ 1, -1, -1]])

In [32]:
b[1,:] = b[1,:] - 2*b[0,:]
b

matrix([[4],
        [1],
        [2]])

In [33]:
A[2,:] = A[2,:] - A[0,:]
b[2,:] = b[2,:] - b[0,:]
A, b

(matrix([[ 1,  1,  1],
         [ 0,  1, -1],
         [ 0, -2, -2]]), matrix([[ 4],
         [ 1],
         [-2]]))

In [34]:
A

matrix([[ 1,  1,  1],
        [ 0,  1, -1],
        [ 0, -2, -2]])

In [35]:
A[2,:] - (-2)*A[1,:]

matrix([[ 0,  0, -4]])

In [36]:
b[2,:] - (-2)*b[1,:]

matrix([[0]])

In [ ]:
def gaus_elim(A_, b_):
    
    A = np.matrix.copy()
    b = np.matrix.copy()
    
    # Tahap eliminasi
    for k in range(N-1):
        A[:,:] = ....
        b[:,:] = ....
        
    # Tahap 
    for i in range(...):
        b[:,:] = ....

    return b