# TF2202 Teknik Komputasi - Sistem Persamaan Linear

Fadjar Fathurrahman

In [1]:
import numpy as np

Pada catatan ini kita kan fokus pada metode untuk mencari solusi dari sistem persamaan linear yang dapat dituliskan dalam bentuk matriks sebagai berikut:
$$
\mathbf{A}\mathbf{x} = \mathbf{b}
$$
di mana $A$ dan $b$ masing-masing diberikan dan tugas kita adalah mencari $\mathbf{x}$.

Sebelum membahas mengenai metode numerik untuk menyelesaikan sistem persamaan linear, kita akan mulai dengan pembahasan mengenai operasi matriks dan vektor dengan dalam Numpy.

## Matrix vs ndarray

`ndarray` adalah tipe array yang paling penting pada Numpy. Untuk merepresentasikan matriks kita dapat menggunakan `ndarray` dengan menggunakan `ndarray` dengan dua dimensi. Untuk merepresentasikan vektor (baris atau kolom) kita dapat menggunakan `ndarray` dengan satu dimensi.

Contoh untuk matriks:
$$
A = \begin{bmatrix}
4 & 1 & 2 & 3 \\
3 & 8 & 1 & 9 \\
3 & 4 & 10 & 4
\end{bmatrix}
$$

Dengan menggunakan `ndarray`, kita dapa mendefinisikan matriks $A$ dengan:

In [8]:
A = np.array([
    [4,1,2,3],
    [3,8,1,9],
    [3,4,10,4]
])
A

array([[ 4,  1,  2,  3],
       [ 3,  8,  1,  9],
       [ 3,  4, 10,  4]])

In [6]:
type(A)

numpy.ndarray

Properti `shape` dapat digunakan untuk mengetahu ukuran dari `ndarray`. Dalam hal ini kita akan mendapatkan tupel berisi dua integer, yang masing-masing integer merupakan jumlah baris dan kolom dari matriks $A$

In [9]:
A.shape

(3, 4)

Anda dapat menuliskan sebagai berikut:

In [15]:
Nrow = A.shape[0]
Ncol = A.shape[1]
print("Nrow = %d, Ncol = %d" % (Nrow, Ncol))

Nrow = 3, Ncol = 4


In [16]:
Nrow, Ncol = A.shape
print("Nrow = %d, Ncol = %d" % (Nrow, Ncol))

Nrow = 3, Ncol = 4


Untuk merepresentasikan vektor, kita dapat menggunakan `ndarray` 1d, misalnya:

In [10]:
x = np.array([3,1,6,7])
x

array([3, 1, 6, 7])

In [8]:
type(x)

numpy.ndarray

Properti `shape` dapat digunakan seperti pada `ndarray` dua dimensi. Pada kasus ini akan dikembalikan tupel dengan satu bilangan integer.

In [17]:
x.shape

(4,)

Fungsi `len` juga dapat digunakan dalam kasus `ndarray` 1d untuk mengetahui jumlah elemen pada suatu vektor:

In [11]:
len(x)

4

Fungsi `len` juga dapat diaplikasikan pada `ndarray` dua dimensi, namun fungsi ini akan mengembalikan banyak elemen pada dimensi pertama.

In [12]:
len(A)

3

Untuk mengetahui jumlah kolom, kita dapat mencari panjang dari `A[0]` (misalnya):

In [18]:
len(A[0])

4

### Operasi perkalian matriks dan vektor

Untuk menghitung operasi perkalian, misalnya $\mathbf{b} = \mathbf{A}\mathbf{x}$.
Untuk tipe `numpy.ndarray` kita dapat menggunakan fungsi `np.matmul`:

In [19]:
b = np.matmul(A,x)
b

array([ 46,  86, 101])

Operator `*` memiliki arti yang berbeda untuk operasi antara dua `ndarray`:

In [17]:
A

array([[ 4,  1,  2],
       [ 3,  8,  1],
       [ 3,  4, 10]])

In [22]:
Ax = A*x
Ax

array([[12,  3,  6],
       [ 9, 24,  3],
       [ 9, 12, 30]])

In [21]:
print(Ax[:,0]/A[:,0])
print(Ax[:,1]/A[:,1])
print(Ax[:,2]/A[:,2])

[3. 3. 3.]
[3. 3. 3.]
[3. 3. 3.]


In [33]:
B = np.matrix([
    [1, 2],
    [3, 4],
    [5, 6]
])
np.matmul(A,B)

matrix([[17, 24],
        [32, 44],
        [65, 82]])

Jika ingin menggunakan operator `*` kita dapat menggunakan konstruktor `np.matrix`.

In [40]:
AA = np.matrix(A)
BB = np.matrix(B)

In [41]:
AA

matrix([[ 4,  1,  2],
        [ 3,  8,  1],
        [ 3,  4, 10]])

In [42]:
BB

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [39]:
type(AA)

numpy.matrixlib.defmatrix.matrix

In [35]:
AA.shape, BB.shape

((3, 3), (3, 2))

In [36]:
AA*BB

matrix([[17, 24],
        [32, 44],
        [65, 82]])

### Perkalian dot (skalar)

Untuk operasi skalar antara dua vektor kita dapat menggunakan fungsi `np.dot`

In [23]:
y = np.array([2,1,3])
y

array([2, 1, 3])

In [24]:
np.dot(y,y)

14

In [25]:
np.dot(x,y)

18

In [26]:
np.dot(x,x)

27

Metode `dot` juga dapat digunakan untuk operasi dot product:

In [27]:
x.dot(x)

27

Operasi `dot` juga dapat digunakan untuk melakukan perkalian antara matriks dengan vektor:

In [29]:
A.dot(x)

array([21, 36, 51])

In [30]:
np.matmul(A,x)

array([21, 36, 51])

Untuk tipe `matrix`:

In [43]:
xx = np.matrix(x).transpose()
xx

matrix([[3],
        [3],
        [3]])

In [46]:
xx.transpose().dot(xx)[0,0]

27

In [47]:
AA.dot(xx)

matrix([[21],
        [36],
        [51]])

In [48]:
AA*xx

matrix([[21],
        [36],
        [51]])

In [51]:
AA.dot(BB)

matrix([[17, 24],
        [32, 44],
        [65, 82]])

In [52]:
AA*BB

matrix([[17, 24],
        [32, 44],
        [65, 82]])

## Metode Eliminasi Gauss

Perhatikan sistem persamaan linear berikut ini:
$$
\begin{align*}
x_{1} + x_{2} + x_{3} & = 4 \\
2x_{1} + 3x_{2} + x_{3} & = 9 \\
x_{1} - x_{2} - x_{3} & = -2
\end{align*}
$$
Persamaan di atas dapat diubah dalam bentuk matrix sebagai
$$
\begin{bmatrix}
1 & 1 & 1 \\
2 & 3 & 1 \\
1 & -1 & -1
\end{bmatrix}
\begin{bmatrix}
x_{1} \\
x_{2} \\
x_{3}
\end{bmatrix}
= 
\begin{bmatrix}
4 \\
9 \\
-2
\end{bmatrix}
$$

In [2]:
A = np.matrix([
    [1, 1, 1],
    [2, 3, -1],
    [1, -1, -1]
])
A

matrix([[ 1,  1,  1],
        [ 2,  3, -1],
        [ 1, -1, -1]])

In [3]:
b = np.matrix([4, 9, 2]).transpose()
b

matrix([[4],
        [9],
        [2]])

Karena kita akan memodifikasi matrix `A` dan `b`, maka kita harus membuat backup (copy) dari nilai asli mereka.

In [4]:
A_orig = np.matrix.copy(A)
b_orig = np.matrix.copy(b)

Untuk reduksi baris kedua

In [5]:
alpha = A[1,0]/A[0,0]
A[1,:] = A[1,:] - alpha*A[0,:]
b[1] = b[1] - alpha*b[0]

In [7]:
A

matrix([[ 1,  1,  1],
        [ 0,  1, -3],
        [ 1, -1, -1]])

In [8]:
b

matrix([[4],
        [1],
        [2]])

In [ ]:
import numpy as np

def gauss_elim(A_, b_):
    
    N, Nrhs = b_.shape

    A = np.matrix.copy(A)
    b = np.matrix.copy(b)

    # Eliminasi
    for k in range(0,N-1):
        for i in range(k+1,N):
            if A[i,k] != 0.0:
                alpha = A[i,k]/A[k,k]
                A[i,k+1:N] = A[i,k+1:N] - alpha*A[k,k+1:N]
                b[i,:] = b[i,:] - alpha*B[k,:]

    # Substitusi balik
    for k in range(N-1,-1,-1):
        B[k,:] = (B[k,:] - np.dot(A[k,k+1:N],B[k+1:N,:]))/A[k,k]
    
    return B

## Menggunakan pustaka pada Python

Untuk berbagai aplikasi pada sains dan teknik, kita biasanya menyelesaikan sistem persamaan linear yang ditemui dengan menggunakan berbagai macam pustaka yang sudah tersedia.

Python sudah memiliki beberapa fungsi yang terkait dengan sistem persamaan linear dan operasi terkait seperti menghitung determinan dan invers matriks.

Fungsi `np.linalg.solve` dapat digunakan untuk menyelesaikan sistem persamaan linear:

In [54]:
A = np.matrix([
    [1, 1, 1],
    [2, 3, -1],
    [1, -1, -1]
])
B = np.matrix([4, 9, 2]).transpose()

In [56]:
x = np.linalg.solve(A,B)
x

matrix([[3.],
        [1.],
        [0.]])

In [57]:
A*x - B

matrix([[0.],
        [0.],
        [0.]])

Fungsi `np.linalg.det` dapat digunakan untuk menghitung determinan dari suatu matriks

In [58]:
np.linalg.det(A)

-8.000000000000002

Fungsi `np.linalg.inv` dapat digunakan untuk menghitung invers dari suatu matriks

In [59]:
np.linalg.inv(A)

matrix([[ 0.5  ,  0.   ,  0.5  ],
        [-0.125,  0.25 , -0.375],
        [ 0.625, -0.25 , -0.125]])