# TF2202 Teknik Komputasi - Sistem Persamaan Linear

Fadjar Fathurrahman

In [1]:
import numpy as np

Pada catatan ini kita kan fokus pada metode untuk mencari solusi dari sistem persamaan linear yang dapat dituliskan dalam bentuk matriks sebagai berikut:
$$
\mathbf{A}\mathbf{x} = \mathbf{b}
$$
di mana $A$ dan $b$ masing-masing diberikan dan tugas kita adalah mencari $\mathbf{x}$.

Perhatikan sistem persamaan linear berikut ini:
$$
\begin{align*}
x_{1} + x_{2} + x_{3} & = 4 \\
2x_{1} + 3x_{2} + x_{3} & = 9 \\
x_{1} - x_{2} - x_{3} & = -2
\end{align*}
$$
Persamaan di atas dapat diubah dalam bentuk matrix sebagai
$$
\begin{bmatrix}
1 & 1 & 1 \\
2 & 3 & 1 \\
1 & -1 & -1
\end{bmatrix}
\begin{bmatrix}
x_{1} \\
x_{2} \\
x_{3}
\end{bmatrix}
= 
\begin{bmatrix}
4 \\
9 \\
-2
\end{bmatrix}
$$

In [2]:
A = np.matrix([
    [1, 1, 1],
    [2, 3, -1],
    [1, -1, -1]
])
A

matrix([[ 1,  1,  1],
        [ 2,  3, -1],
        [ 1, -1, -1]])

In [3]:
b = np.matrix([4, 9, 2]).transpose()
b

matrix([[4],
        [9],
        [2]])

Karena kita akan memodifikasi matrix `A` dan `b`, maka kita harus membuat backup (copy) dari nilai asli mereka.

In [4]:
A_orig = np.matrix.copy(A)
b_orig = np.matrix.copy(b)

Untuk reduksi baris kedua

In [5]:
alpha = A[1,0]/A[0,0]
A[1,:] = A[1,:] - alpha*A[0,:]
b[1] = b[1] - alpha*b[0]

In [7]:
A

matrix([[ 1,  1,  1],
        [ 0,  1, -3],
        [ 1, -1, -1]])

In [8]:
b

matrix([[4],
        [1],
        [2]])

In [ ]:
import numpy as np

def gauss_elim(A_, b_):
    
    N, Nrhs = b_.shape

    A = np.matrix.copy(A)
    b = np.matrix.copy(b)

    # Eliminasi
    for k in range(0,N-1):
        for i in range(k+1,N):
            if A[i,k] != 0.0:
                alpha = A[i,k]/A[k,k]
                A[i,k+1:N] = A[i,k+1:N] - alpha*A[k,k+1:N]
                b[i,:] = b[i,:] - alpha*B[k,:]

    # Substitusi balik
    for k in range(N-1,-1,-1):
        B[k,:] = (B[k,:] - np.dot(A[k,k+1:N],B[k+1:N,:]))/A[k,k]
    
    return B # return the matrix, not just the slice