<h1 style="text-align: center;">TF2202 Komputasi Rekayasa - Latihan Numpy</h1>

# Setup

In [1]:
import numpy as np

In [2]:
import IPython.display
from IPython.display import Markdown

Some functions for pretty-printing matrix in notebook:

In [3]:
def colvec_to_tex(v):
    assert len(v.shape) == 1
    lines = str(v).replace('[', '').replace(']', '').split()
    rv = r'\begin{bmatrix}'
    for l in lines:
        rv = rv + l + r" \\"
    rv +=  r'\end{bmatrix}'
    return rv

# Sumber:
# https://stackoverflow.com/questions/17129290/numpy-2d-and-1d-array-to-latex-bmatrix
def matrix_to_tex(a):
    """Returns a LaTeX bmatrix

    :a: numpy array
    :returns: LaTeX bmatrix as a string
    """
    if len(a.shape) > 2:
        raise ValueError('bmatrix can at most display two dimensions')
    lines = str(a).replace('[', '').replace(']', '').splitlines()
    rv = [r'\begin{bmatrix}']
    rv += ['  ' + ' & '.join(l.split()) + r'\\' for l in lines]
    rv +=  [r'\end{bmatrix}']
    return '\n'.join(rv)

def show_matrix(a):
    IPython.display.display(Markdown(matrix_to_tex(a)))
    
def show_col_vector(a):
    IPython.display.display(Markdown(colvec_to_tex(a)))

# Pendahuluan

Pada catatan ini kita akan fokus pada metode untuk mencari solusi dari sistem persamaan linear yang dapat dituliskan dalam bentuk matriks sebagai berikut:
$$
\mathbf{A}\mathbf{x} = \mathbf{b}
$$
di mana $A$ dan $b$ masing-masing diberikan dan tugas kita adalah mencari $\mathbf{x}$.

Sebelum membahas mengenai metode numerik untuk menyelesaikan sistem persamaan linear, kita akan mulai dengan pembahasan mengenai operasi matriks dan vektor dengan dalam Numpy.

## List

List pada Python dapat digunakan untuk menyatakan kompulan angka seperti vektor atau matriks.

In [4]:
my_lst = [
    [4,1,2,3],
    [3,8,1,9],
    [3,4,10,4]
]

Pada kuliah di TPB, Anda mungkin mengenal penggunakan `list` ini pada bahasan mengenai array.

List pada Python sebenarnya memiliki fitur yang lebih luas dibandingkan dengan array pada bahasa pemrograman lain, misalnya C++. Misalnya, tipe data pada pada `list` tidak harus seragam:

In [5]:
my_lst1 = [
    ["aaaa",1,2,3],
    [3,8,1,9],
    [3,4,10,4]
]

In [6]:
type(my_lst)

list

In [8]:
my_lst[2]

[3, 4, 10, 4]

## Matrix vs ndarray

Untuk kebutuhan *technical/scientific computing* pada Python, kita biasanya menggunakan pustaka NumPy yang menyediakan array multidimensional dengan tipe data seragam. Array pada NumPy lebih teroptimasi dibandingkan dengan `list` sehingga cocok untuk digunakan pada perhitungan numerik yang berat atau kompleks.

`ndarray` adalah tipe array yang paling penting pada Numpy. Untuk merepresentasikan matriks kita dapat menggunakan `ndarray` dengan menggunakan `ndarray` dengan dua dimensi. Untuk merepresentasikan vektor (baris atau kolom) kita dapat menggunakan `ndarray` dengan satu dimensi.

Contoh untuk matriks:
$$
A = \begin{bmatrix}
4 & 1 & 2 & 3 \\
3 & 8 & 1 & 9 \\
3 & 4 & 10 & 4
\end{bmatrix}
$$

Dengan menggunakan `list`, kita dapat mendefinisikan matrix $A$ sebagai berikut

In [9]:
A_list = [
  [4,1,2,3],
  [3,8,1,9],
  [3,4,10,4]  
]
A_list

[[4, 1, 2, 3], [3, 8, 1, 9], [3, 4, 10, 4]]

In [12]:
type(A_list)

list

Dengan menggunakan `ndarray`, kita dapa mendefinisikan matriks $A$ dengan:

In [10]:
A = np.array([
    [4,1,2,3],
    [3,8,1,9],
    [3,4,10,4]
])
A

array([[ 4,  1,  2,  3],
       [ 3,  8,  1,  9],
       [ 3,  4, 10,  4]])

In [11]:
type(A)

numpy.ndarray

Alternatif lain:

In [13]:
A = np.array(A_list)

In [14]:
type(A)

numpy.ndarray

Properti `shape` dapat digunakan untuk mengetahu ukuran dari `ndarray`. Dalam hal ini kita akan mendapatkan tupel berisi dua integer, yang masing-masing integer merupakan jumlah baris dan kolom dari matriks $A$

In [15]:
A.shape

(3, 4)

In [19]:
A

array([[ 4,  1,  2,  3],
       [ 3,  8,  1,  9],
       [ 3,  4, 10,  4]])

In [18]:
A.transpose()

array([[ 4,  3,  3],
       [ 1,  8,  4],
       [ 2,  1, 10],
       [ 3,  9,  4]])

In [20]:
A.diagonal()

array([ 4,  8, 10])

Anda dapat menuliskan sebagai berikut:

In [24]:
res = A.shape

Tuple mirip dengan list

In [22]:
Nrow = A.shape[0]
Ncol = A.shape[1]
print("Nrow = %d, Ncol = %d" % (Nrow, Ncol))

Nrow = 3, Ncol = 4


In [23]:
Nrow, Ncol = A.shape
print("Nrow = %d, Ncol = %d" % (Nrow, Ncol))

Nrow = 3, Ncol = 4


Untuk merepresentasikan vektor, kita dapat menggunakan `ndarray` 1d, misalnya:

In [27]:
x = np.array([3,1,6,7])
x

array([3, 1, 6, 7])

In [28]:
type(x)

numpy.ndarray

In [33]:
A.size

12

In [ ]:
A.size

In [36]:
A

array([[ 4,  1,  2,  3],
       [ 3,  8,  1,  9],
       [ 3,  4, 10,  4]])

In [37]:
show_matrix(A)

\begin{bmatrix}
  4 & 1 & 2 & 3\\
  3 & 8 & 1 & 9\\
  3 & 4 & 10 & 4\\
\end{bmatrix}

In [38]:
show_matrix(A.T)

\begin{bmatrix}
  4 & 3 & 3\\
  1 & 8 & 4\\
  2 & 1 & 10\\
  3 & 9 & 4\\
\end{bmatrix}

Properti `shape` dapat digunakan seperti pada `ndarray` dua dimensi. Pada kasus ini akan dikembalikan tupel dengan satu bilangan integer.

In [ ]:
x.shape

Fungsi `len` juga dapat digunakan dalam kasus `ndarray` 1d untuk mengetahui jumlah elemen pada suatu vektor:

In [ ]:
len(x)

Fungsi `len` juga dapat diaplikasikan pada `ndarray` dua dimensi, namun fungsi ini akan mengembalikan banyak elemen pada dimensi pertama.

In [ ]:
len(A)

Untuk mengetahui jumlah kolom, kita juga dapat mencari panjang dari `A[0]` (misalnya):

In [ ]:
len(A[0])

## Operasi dengan ndarray

In [41]:
A = np.array([
    [4.0,1.0,2,3],
    [3.0,8,1,9],
    [3,4,10,4]
])
A

array([[ 4.,  1.,  2.,  3.],
       [ 3.,  8.,  1.,  9.],
       [ 3.,  4., 10.,  4.]])

In [42]:
A.dtype

dtype('float64')

In [40]:
A = np.array([
    [4,1,2,3],
    [3,8,1,9],
    [3,4,10,4]
], dtype=np.float64)
A

array([[ 4.,  1.,  2.,  3.],
       [ 3.,  8.,  1.,  9.],
       [ 3.,  4., 10.,  4.]])

Mengakses elemen

In [43]:
A[0,2]

2.0

Menulis nilai ke suatu elemen

In [44]:
A[0,2] = 999.0

In [45]:
A

array([[  4.,   1., 999.,   3.],
       [  3.,   8.,   1.,   9.],
       [  3.,   4.,  10.,   4.]])

Slicing:

In [46]:
A[:,0]

array([4., 3., 3.])

In [47]:
A[:,1]

array([1., 8., 4.])

In [49]:
A[:,1:3]

array([[  1., 999.],
       [  8.,   1.],
       [  4.,  10.]])

In [50]:
A[1,:]

array([3., 8., 1., 9.])

In [53]:
show_matrix(A)

\begin{bmatrix}
  4. & 1. & 999. & 3.\\
  3. & 8. & 1. & 9.\\
  3. & 4. & 10. & 4.\\
\end{bmatrix}

In [52]:
show_matrix(A[1,:])

\begin{bmatrix}
  3. & 8. & 1. & 9.\\
\end{bmatrix}

In [51]:
show_col_vector(A[1,:])

\begin{bmatrix}3. \\8. \\1. \\9. \\\end{bmatrix}

In [ ]:
show_matrix(A[:,1])

In [73]:
A = np.array([
    [1.0, 1.0, 1.0],
    [2.0, 3.0, 1.0],
    [1.0, -1.0, -1.0]
])

In [55]:
b = np.array([4.0, 9.0, -2.0])

In [56]:
show_matrix(A)

\begin{bmatrix}
  1. & 1. & 1.\\
  2. & 3. & 1.\\
  1. & -1. & -1.\\
\end{bmatrix}

In [57]:
show_col_vector(b)

\begin{bmatrix}4. \\9. \\-2. \\\end{bmatrix}

In [91]:
Z = np.array([
    [0.0, 2, 8],
    [1.0, 3, 4]
])

In [92]:
show_matrix(Z)

\begin{bmatrix}
  0. & 2. & 8.\\
  1. & 3. & 4.\\
\end{bmatrix}

In [95]:
W = np.copy(Z)

In [96]:
show_matrix(W)

\begin{bmatrix}
  0. & 2. & 8.\\
  1. & 3. & 4.\\
\end{bmatrix}

In [97]:
W[0,0] = 9999.0

In [98]:
show_matrix(W)

\begin{bmatrix}
  9.999e+03 & 2.000e+00 & 8.000e+00\\
  1.000e+00 & 3.000e+00 & 4.000e+00\\
\end{bmatrix}

In [99]:
show_matrix(Z)

\begin{bmatrix}
  0. & 2. & 8.\\
  1. & 3. & 4.\\
\end{bmatrix}

In [74]:
A_orig = np.copy(A)
b_orig = np.copy(b)

Operasi pada baris kedua

In [75]:
A

array([[ 1.,  1.,  1.],
       [ 2.,  3.,  1.],
       [ 1., -1., -1.]])

In [76]:
A[1,:] = A[1,:] - 2*A[0,:]

In [77]:
show_matrix(A)

\begin{bmatrix}
  1. & 1. & 1.\\
  0. & 1. & -1.\\
  1. & -1. & -1.\\
\end{bmatrix}

In [78]:
A[2,:] = A[2,:] - A[0,:]

In [79]:
show_matrix(A)

\begin{bmatrix}
  1. & 1. & 1.\\
  0. & 1. & -1.\\
  0. & -2. & -2.\\
\end{bmatrix}

In [80]:
A[2,:] = A[2,:] - (-2)*A[1,:]

In [81]:
show_matrix(A)

\begin{bmatrix}
  1. & 1. & 1.\\
  0. & 1. & -1.\\
  0. & 0. & -4.\\
\end{bmatrix}

 ### Operasi perkalian matriks dan vektor

Untuk menghitung operasi perkalian, misalnya $\mathbf{b} = \mathbf{A}\mathbf{x}$.
Untuk tipe `numpy.ndarray` kita dapat menggunakan fungsi `np.matmul`:

`np.matmul` juga sering digunakan untuk operasi kontraksi tensor (tensor contraction).

In [ ]:
A

In [ ]:
x

In [ ]:
b = np.matmul(A,x)
b

Operator `*` memiliki arti yang berbeda untuk operasi antara dua `ndarray`:

In [ ]:
A

In [ ]:
x

In [ ]:
Ax = A*x
Ax

In [ ]:
3*A[0]

In [ ]:
print(Ax[:,0]/A[:,0])
print(Ax[:,1]/A[:,1])
print(Ax[:,2]/A[:,2])

Jika ingin menggunakan operator `*` kita dapat menggunakan konstruktor `np.matrix`.

In [ ]:
B = np.random.rand(4,4)
B

In [ ]:
AA = np.matrix(A)
BB = np.matrix(B)

In [ ]:
AA

In [ ]:
BB

In [ ]:
type(AA)

In [ ]:
AA.shape, BB.shape

Operator `*` dapat digunakan untuk melakukan operasi perkalian matrix antara dua variabel dengan tipe `numpy.matrix`.

In [ ]:
AA*BB

In [ ]:
show_matrix(AA*BB)

### Perkalian dot (skalar)

Untuk operasi skalar antara dua vektor kita dapat menggunakan fungsi `np.dot`

In [ ]:
y = np.array([2,1,3,6])
y

In [ ]:
np.dot(y,y)

In [ ]:
np.dot(x,y)

In [ ]:
np.dot(x,x)

Metode `dot` juga dapat digunakan untuk operasi dot product:

In [ ]:
x.dot(x)

Operasi `dot` juga dapat digunakan untuk melakukan perkalian antara matriks dengan vektor:

In [ ]:
A.dot(x)

In [ ]:
np.matmul(A,x)

Untuk tipe `numpy.matrix`:

In [ ]:
xx = np.matrix(x).transpose()
xx

In [ ]:
xx.transpose().dot(xx)[0,0]

In [ ]:
AA.dot(xx)

In [ ]:
AA*xx

In [ ]:
show_matrix(AA*xx)

In [ ]:
show_matrix( AA.dot(BB) )

In [ ]:
show_matrix( AA*BB )

Pada catatan ini, kita akan menggunakan `matrix`. Jika Anda lebih suka menggunakan `ndarray` langsung, Anda harus melakukan beberapa modifikasi.

Operasi vektorisasi sebisa mungkin akan dihindari agar struktur loop terlihat secara eksplisit.